### ISSUE TITLE
Can't figure out how to submit a farm

### ISSUE THREAD

**Issue by GriffGreen** [1Hive/honeyswap-unipool-frontend#13]
<img width="1426" alt="Screen Shot 2020-10-16 at 8 26 14 PM" src="https://user-images.githubusercontent.com/14945613/96295395-1d1cec80-0fee-11eb-93d0-0abbec894cd2.png">

It just loads?

**Comment by fbgoat** [comment]
Closing this issue, since its not really an issue anymore.
